# Generated by Django 3.0.6 on 2020-05-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=75, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
